### ISSUE TITLE
Error on installing requirements

### ISSUE THREAD

**Issue by nDman** [yeppiidev/qemu-manager#1]
When I try to install requirements I get this error:
```
ERROR: Could not find a version that satisfies the requirement atexit (from versions: none)
ERROR: No matching distribution found for atexit
```
I use Python 3.11.1

**Comment by yeppiidev** [comment]
Fixed in the latest commit 👍🏼 Feel free to reopen this issue if you experience any more errors :D

**Comment by nDman** [comment]
> Fixed in the latest commit 👍🏼 Feel free to reopen this issue if you experience any more errors :D

Awesome, thank you.
